import type { Metadata } from "next";
import { Raleway, Montserrat , Poppins } from "next/font/google";
import "./globals.css";
import Hero from "./components/Hero"
import Info from "./components/Info";
import About from "./components/About";
import Skills from "./components/Skills";
import Contact from "./components/Contact";


const raleway = Raleway({ subsets: ['latin'], weight: ['400', '700'] })
const montserrat = Montserrat({ subsets: ['latin'], weight: ['400', '700'] })

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={` ${raleway.className} ${montserrat.className} ${poppins.className} font-sans `}>
        <Hero />
        <Info />
        <About />
        <Skills />
        <Contact />
        {children}
      </body>
    </html>
  );
}
